#!/bin/csh -f

echo 'extracting timecourses'
#roidecompose \
    #HCPdatafile.nii.gz \
    #Hutch17CortStriatAmyg_MNI_corrected.nii.gz \
    #output/orig_hcptcs.txt \
    #--pctnorm

echo 'calculating kmeans'
#capfromtcs -i output/orig_hcptcs_corr.txt -o output/orig_hcp --sampletime=0.72 --quality --GBR --varnorm
capfromtcs -i output/rapidtide_hcptcs_corr.txt -o output/rapidtide_hcp --sampletime=0.72 --quality --GBR --varnorm
#capfromtcs -i output/orig_hcptcs_corr.txt -o output/orig_hcp_lfo --sampletime=0.72 -L --quality --GBR --varnorm
#capfromtcs -i output/rapidtide_hcptcs_corr.txt -o output/rapidtide_hcp_lfo --sampletime=0.72 -L --quality --GBR --varnorm

echo 'remapping onto rosi states'
statematch rosi_orig.txt output/orig_hcp_statelabels.txt output/orig
#statematch rosi_rapidtide.txt output/rapidtide_hcp_statelabels.txt output/rapidtide
#statematch rosi_orig.txt output/orig_hcp_lfo_statelabels.txt output/orig_lfo
#statematch rosi_rapidtide.txt output/rapidtide_hcp_lfo_statelabels.txt output/rapidtide_lfo

echo 'projecting clusters back onto the brain'
#roirecompose output/orig_hcp_clustercenters.txt Hutch17CortStriatAmyg_MNI_corrected.nii.gz output/orig_states
#roirecompose output/rapidtide_hcp_clustercenters.txt Hutch17CortStriatAmyg_MNI_corrected.nii.gz output/rapidtide_states

#fslview output/orig_states -l Hot -b 0.1,2 output/rapidtide_states -l Hot -b 0.1,2
