#!/bin/csh -f

echo 'extracting timecourses'
#roidecompose Resting_101309/REST1_LR/origional/101309_Hutch17CortStriatAmyg_MNI_REST1_LR.txt \
#    Hutch17CortStriatAmyg_MNI.nii.gz \
#    orig_hcptcs.txt \
#    --stdnorm
#cp Resting_101309/REST1_LR/origional/101309_Hutch17CortStriatAmyg_MNI_REST1_LR.txt output/orig_hcptcs.txt
#roidecompose Resting_101309/REST1_LR/rapidtide/101309_rapidtide_Hutch17CortStriatAmyg_MNI_REST1_LR.txt \
#    Hutch17CortStriatAmyg_MNI.nii.gz \
#    rapidtide_hcptcs.txt \
#    --stdnorm
#cp Resting_101309/REST1_LR/rapidtide/101309_rapidtide_Hutch17CortStriatAmyg_MNI_REST1_LR.txt output/rapidtide_hcptcs.txt

echo 'calculating kmeans'
capfromtcs -i manyfiles.txt -o output/manyfiles --sampletime=0.72 --varnorm -m -b 4800 -S 1200 --quality -E default --minlength=2

echo 'checking for existence of trained model file'
ls -ltra output/manyfiles.joblib

echo 'rerunning with trained model'
capfromtcs -i manyfiles.txt -o output/reloaded_manyfiles --sampletime=0.72 --varnorm -m -b 4800 -S 1200 --quality -E default --modelroot=output/manyfiles

echo 'projecting clusters back onto the brain'
roirecompose output/manyfiles_clustercenters.txt Hutch17CortStriatAmyg_MNI.nii.gz output/manyfiles_states

fslview output/manyfiles_states -l Hot -b 0.1,2
