#!/bin/csh -f
capfromtcs \
    -i /Users/frederic/Dropbox_PHC/connectome_quality/100307/preproc/100307/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz \
    -i /Users/frederic/Dropbox_PHC/connectome_quality/100307/preproc/100307/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz \
    -o output/noparcel \
    --maskname=/Users/frederic/Dropbox_PHC/awsspeedcomparison/HCP_1200/100206/rapidtide_rfMRI_REST1_LR_desc-corrfit_mask.nii.gz \
    --sampletime=0.72 \
    --varnorm \
    -p 12 \
    -m \
    --quality \
    -S 1200 \
    -E default \
    --sigma=3.0 \
    --minout=2
