#!/bin/bash

conda create --name capcalc
conda activate capcalc
conda install \
        numpy \
        scipy \
        scikit-learn \
        matplotlib \
        statsmodels \
        pyfftw \
        nibabel \
        versioneer
